# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenca', '0002_auto_20161029_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dataAdmissao',
            field=models.DateField(verbose_name='Data admissao'),
        ),
        migrations.AlterField(
            model_name='licenca',
            name='dataDeferimento',
            field=models.DateField(verbose_name='Data do deferimento'),
        ),
        migrations.AlterField(
            model_name='recusa',
            name='data',
            field=models.DateField(verbose_name='Data de recusa'),
        ),
        migrations.AlterField(
            model_name='requerimentolicenca',
            name='dataLicenca',
            field=models.DateField(verbose_name='Data desejada'),
        ),
        migrations.AlterField(
            model_name='requerimentolicenca',
            name='dataRequisicao',
            field=models.DateField(verbose_name='Data de requisicao'),
        ),
        migrations.AlterField(
            model_name='revogacao',
            name='data',
            field=models.DateField(verbose_name='Data de revogacao'),
        ),
    ]
