# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licenca', '0005_auto_20161108_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario_Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(verbose_name='Data de Inicio')),
                ('dataTermino', models.DateField(verbose_name='Data de Termino')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenca.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario_Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(verbose_name='Data de Inicio')),
                ('dataTermino', models.DateField(verbose_name='Data de Termino')),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='setor',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requerimentolicenca',
            name='status',
            field=models.CharField(choices=[(b'AV', b'AVALIACAO'), (b'RE', b'RECUSADA'), (b'AP', b'APROVADA'), (b'RV', b'REVOGADA'), (b'CA', b'CANCELADA')], default='AV', max_length=2),
        ),
        migrations.AddField(
            model_name='funcionario_setor',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenca.Funcionario'),
        ),
        migrations.AddField(
            model_name='funcionario_setor',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenca.Setor'),
        ),
        migrations.AddField(
            model_name='funcionario_cargo',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenca.Funcionario'),
        ),
    ]
