# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenca', '0006_auto_20161108_2309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario_Cargo',
            new_name='FuncionarioCargo',
        ),
        migrations.RenameModel(
            old_name='Funcionario_Setor',
            new_name='FuncionarioSetor',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dataAdmissao',
            field=models.DateField(verbose_name='Data Admissao'),
        ),
    ]
