# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenca', '0007_auto_20161111_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuncionarioCargo',
            new_name='Funcao',
        ),
        migrations.RenameModel(
            old_name='FuncionarioSetor',
            new_name='Lotacao',
        ),
    ]
